name: publish-docs

on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3.2.0
    - name: Set up Python 3.x
      uses: actions/setup-python@v4.4.0
      with:
        python-version: "3.x"
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
    - name: Install Package
      run: poetry install
    - name: Build and deploy docs
      run:  poetry run mkdocs gh-deploy --clean --strict --verbose --force
