name: quality-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.platform }}
    env:
      PLATFORM: ${{ matrix.platform }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      PYTHONUTF8: 1  # https://peps.python.org/pep-0540/
      COLORTERM: truecolor
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.3.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
      - name: Install Package
        run: poetry install
      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files --show-diff-on-failure --color=always
      - name: Make sure we can build the package
        run: poetry build -vvv
      - name: Test code
        run: poetry run pytest -v --cov --cov-report=xml --durations=20
      - name: Test docs
        run: poetry run mkdocs build --clean --strict --verbose
      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          env_vars: PLATFORM,PYTHON_VERSION
          fail_ci_if_error: false

  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.0
        with:
          install: true
      - name: Build Image
        uses: docker/build-push-action@v3.3.0
        with:
          file: ./docker/Dockerfile
          pull: true
          push: false
